nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: 
            - 'http://localhost:5173'
            - 'http://localhost:5174'
            - 'https://localhost:5173'
            - 'https://localhost:5174'
            - 'https://e-tawjihi.ma'
            - 'https://www.e-tawjihi.ma'
            - 'https://e-tawjihi.com'
            - 'https://www.e-tawjihi.com'
            - 'https://new.e-tawjihi.ma'
            - 'https://www.new.e-tawjihi.ma'
            - 'https://apinew.e-tawjihi.ma'
            - 'https://www.apinew.e-tawjihi.ma'
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
        expose_headers: ['Link']
        max_age: 3600
        allow_credentials: true
    paths:
        '^/api': ~
        '^/': ~
